name: cultivate life
favicon: null
layout_spectrum: 0.25072
typography_spectrum: 0.55106
title: cultivate life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffcb8d'
    - '#5f5d6a'
    - '#7d99ba'
    - '#020202'
    - '#bf7a44'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
