name: cultivate life
favicon: null
layout_spectrum: 0.99693
typography_spectrum: 0.55106
title: cultivate life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231616'
    - '#e6c8bc'
    - '#9e9193'
    - '#403b38'
    - '#70706e'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
