typography_spectrum: 0.40288
color:
  brandColors:
    - '#3c2936'
    - '#3e546a'
    - '#1a0003'
    - '#899a79'
    - '#4e8583'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.49387
analytics:
  google: null
  facebook: null
  twitter: null
name: cultivate life
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: listen
    id: 96630386-d28e-47bd-a53c-f283329fef84
    type: content
  - name: eat
    id: 2fb070c1-e725-43ec-8458-7feee2575f84
    type: content
favicon: null
title: cultivate life
purpose: []
