name: cultivate life
favicon: null
layout_spectrum: 0.25072
typography_spectrum: 0.55106
title: cultivate life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#323338'
    - '#fffeef'
    - '#897159'
    - '#d1bda2'
    - '#a88a64'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
