name: cultivate-life
favicon: null
layout_spectrum: 0.25072
typography_spectrum: 0.55106
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#535550'
    - '#0d111d'
    - '#ffae54'
    - '#fffff2'
    - '#e67927'
  brandStrength: 1
  lightness: 0.9130185302346945
  saturation: 0.6875
  rhythmicContrast: 0.546930075623095
purpose: []
