name: cultivate life
favicon: null
layout_spectrum: 0.49387
typography_spectrum: 0.40288
title: cultivate life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3c2936'
    - '#3e546a'
    - '#1a0003'
    - '#899a79'
    - '#4e8583'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
